[package]
name = "psx-trace-ingestor"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tokio-postgres = { version = "0.7", features = ["with-serde_json-1"] }
serde_json = "1.0"
futures-util = "0.3"
bytes = "1.0"
